apiVersion: v1
kind: Secret
metadata:
  name: infra.ghcr-credentials
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiIiwicGFzc3dvcmQiOiIiLCJlbWFpbCI6IiIsImF1dGgiOiIifX19
type: kubernetes.io/dockerconfigjson
