apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../more-cars
  - namespace.yaml
  - analytics-db-service.yaml
  - analytics-db-deployment.yaml
  - analytics-db-pvc.yaml
  - analytics-service.yaml
  - analytics-deployment.yaml
  - analytics-pvc.yaml
  - analytics-https-route.yaml
  - analytics-health-check.yaml

namespace: prod

patches:
  - path: analytics.patch.json
    target:
      kind: HTTPRoute
      name: analytics-https
  - target:
      kind: Gateway
      name: more-cars-gateway
    patch: |
      - op: add
        path: /spec/listeners/-
        value:
          name: more-cars-public-http
          port: 80
          protocol: HTTP
          hostname: "*.more-cars.net"
      - op: add
        path: /spec/listeners/-
        value:
          name: more-cars-public-https
          port: 443
          protocol: HTTPS
          hostname: "*.more-cars.net"
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                name: infra.more-cars-certificate
