apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - analytics-db-service.yaml
  - analytics-db-deployment.yaml
  - analytics-db-pvc.yaml
  - analytics-service.yaml
  - analytics-deployment.yaml
  - analytics-pvc.yaml
  - analytics-https-route.yaml
  - analytics-health-check.yaml

namespace: prod

patches:
  - path: analytics.patch.json
    target:
      kind: HTTPRoute
      name: analytics-https
