apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-db
  template:
    metadata:
      labels:
        app: analytics-db
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-db-credentials
                  key: password
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-db-credentials
                  key: password
            - name: MARIADB_DATABASE
              value: "matomo"
            - name: MARIADB_USER
              value: "matomo"
          resources:
            requests:
              cpu: "5m"
              memory: "150Mi"
          volumeMounts:
            - name: analytics-db
              mountPath: /var/lib/mysql
      volumes:
        - name: analytics-db
          persistentVolumeClaim:
            claimName: analytics-db
