apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - pocket-id-pvc.yaml
  - pocket-id-deployment.yaml
  - pocket-id-service.yaml
  - pocket-id-https-route.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - oauth2-proxy-health-check.yaml

patches:
  - path: gateway.patch.json
    target:
      kind: Gateway
      name: more-cars-gateway
  - path: pocket-id-deployment.patch.json
    target:
      kind: Deployment
      name: pocket-id
  - path: pocket-id-route.patch.json
    target:
      kind: HTTPRoute
      name: pocket-id
  - path: oauth2-proxy-deployment.patch.json
    target:
      kind: Deployment
      name: oauth2-proxy
